apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-10-tenant/load-app-256abab4-6a14-4161-90f1-7cb38e47fa02/devfile-sample-python-basic@sha256:d326b0897d645042c2f1c2130cc46a23bc04a6c3bd8cacc5fa489b0c62c06ae6
        name: my-python
        resources: {}
status: {}
